name: general_dialog
description: Simple dialog that not uses context.
version: 0.0.1
author: Flutterando Team <david@flutterando.com.br>
homepage: https://flutterando.com.br/
git: https://github.com/davidsdearaujo/find_dropdown
repository: https://github.com/davidsdearaujo/find_dropdown

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
